version: "3.1"
services:
  webman-rqueue-php:
    restart: always
    container_name: webman-rqueue-php
    build:
      context: ./
    volumes:
      - ./:/var/www
    logging:
      driver: json-file
      options:
        max-size: "20m"
        max-file: "10"
    tty: true
  redis:
    restart: always
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
